name: Healther
main: Palente\Healther\Main
author: Palente
version: 0.0.1
api: [3.0.0-ALPHA11,3.0.0-ALPHA12]
description: "Heal command, Pay to be healed"
depend: EconomyAPI

commands:
  heal:
  description: "Pay to be healed"
  permission: healther.use
